# Generated by Django 3.1.4 on 2020-12-11 23:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Table name')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('subject', models.CharField(max_length=250, null=True, verbose_name='Task subject')),
                ('status', models.CharField(choices=[('To do', 'To do'), ('In progress', 'In progress'), ('Ready for test', 'Ready for test'), ('Closed', 'Closed')], max_length=200, null=True)),
                ('description', ckeditor.fields.RichTextField(null=True, verbose_name='Task description')),
                ('table_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t_t.table')),
            ],
        ),
    ]
