# Generated by Django 3.1.4 on 2020-12-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_t', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
