# Generated by Django 3.1.4 on 2020-12-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t_t', '0003_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='slug',
        ),
    ]
