# Generated by Django 3.1.4 on 2020-12-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_t', '0005_auto_20201214_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To do', 'To do'), ('In progress', 'In progress'), ('Ready for test', 'Ready for test'), ('Closed', 'Closed')], default='To do', max_length=200),
        ),
    ]
