# Generated by Django 3.1.4 on 2020-12-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_t', '0006_auto_20201214_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='images',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_title',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
